version: 2

models:
  - name: stg_model_4
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: int_model_4
    columns:
      - name: id
        tests:
          - unique
          - not_null
